services:
  backend_inicial:
    image: fercdevv/checker_backend_inicial:latest
    container_name: backend_inicial
    ports:
      - 3000:3000
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  service_monitor:
    image: fercdevv/checker_service_monitor:latest
    container_name: service_monitor
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BACKEND_INICIAL_NAME: backend_inicial
      BACKEND_INICIAL_HOST: backend_inicial
      BACKEND_INICIAL_PORT: 3000
    ports:
      - 4000:4000
    depends_on:
      - redis
      - backend_inicial
  web_nginx:
    image: fercdevv/checker_web_nginx:latest
    container_name: nginx_web
    ports:
      - 8080:80
    